---
mongo_host: 10.0.15.22 # "{{ hostvars['node2']['ansible_eth1']['ipv4']['address'] }}"
elasticsearch_host: 10.0.15.22 #"{{ hostvars['node2']['ansible_eth1']['ipv4']['address'] }}"
elasticsearch_port: 9200
