---
sudo: required

services:
  - docker

before_install:
  # Add current user to docker group and build image
  - sudo usermod -aG docker $(whoami)
  - docker build --rm=true --file=./tests/Dockerfile --tag=ubuntu:ansible tests

script:
  # start container
  - container_id=$(mktemp)
  - docker run --detach --privileged --volume="${PWD}":/etc/ansible/roles/test_role:ro ubuntu:ansible /sbin/init > ${container_id}

  # check syntax and test role
  - docker exec --tty "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/test_role/tests/test.yml --syntax-check
  - docker exec --tty "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/test_role/tests/test.yml

  # ensure mongodb is installed and running
  - docker exec --tty "$(cat ${container_id})" which mongod
  - docker exec -ti "$(cat ${container_id})" bash -c 'systemctl status mongodb | grep -q "active (running)" '
    && (echo 'Service is up' && exit 0)
    || (echo 'Service is down' && exit 1)

  # cleanup
  - docker stop "$(cat ${container_id})"


notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/