---

- name: Add the  apt key
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10 state=present 

- name: Add mongo repository
# apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse' state=present
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' state=present

#- name: Update.
 # command: apt-get update

- name: Install MongoDB.
  command: apt-get install -y mongodb-org
  
#- name: Install MongoDB.
 # apt: pkg=mongodb-org state=present update_cache=yes

- name: ensure mongodb is not running
  service: name=mongod state=stopped enabled=no

- name: ensure db directory exists
  file: path=/data/db state=directory

- name: ensure configdb directory exists
  file: path=/data/configdb state=directory
  notify: Restart mongo

#- name: Install nodejs and some dependencies
 # apt: name=mongodb-org update_cache=yes state=present
  #notify: Start mongo

#- name: bind address to the private ip
 # lineinfile: dest=/etc/mongod.conf regexp='^bind_ip' line='bind_ip=127.0.0.1,{{ ansible_eth1.ipv4.address }}'
 # notify: Restart mongo
