- name: Create the user(s)
  user: name={{ item.name }} shell=/bin/bash state=present
  with_items: user

#- name: Add user ssh keys
  #authorized_key: user={{ item.name }} key="{{ item.key }}"
 # authorized_key: user=vagrant 
  #                  key="{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}" state=present
 # with_items: user

- name: install ssh key
  authorized_key: user=root
                    key="{{ lookup('file', '/var/lib/jenkins/.ssh/test.pem') }}"
                    state=present
